- name: Create fish config directory
  file:
    path: ~/.config/fish
    state: directory

- name: Create fish symlinks
  file:
    src: "{{ ansible_env.PWD }}/roles/fish/files/.fishrc"
    path: "~/.config/fish/.fishrc"
    state: link
    force: yes
