- name: Move nvim file as backup
  command: mv ~/.config/nvim ~/.config/nvimbackup

- name: Clone Astrovim
  git:
    repo: https://github.com/kabinspace/AstroVim
    dest: ~/.config/nvim
    clone: yes
    update: yes

- name: Packer sync
  command: nvim +PackerSync
