- name: Downloading Lunarvim
  get_url:
    url: https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh
    dest: /tmp/install.sh

- name: Installing pexpect
  pip:
    name: pexpect

- name: Create lvim config directory
  file:
    path: ~/.config/lvim
    state: directory
    
- name: Create Lunarvim symlinks
  file:
    src: "~/.dotfiles/roles/lunarvim/files/config.lua"
    path: "~/.config/lvim/config.lua"
    state: link
    force: yes

- name: Installing Lunarvim
  expect:
    command: bash /tmp/install.sh
    timeout: 5
    echo: yes
    responses:
      # 'NodeJS dependencies': n
      # 'Python dependencies': y
      # 'Rust': n
      'default: no': n

- name: Adding lvim to Fish Path
  command: fish -c 'fish_add_path -m ~/.local/bin'

- name: Adding lvim to $PATH
  shell: echo $PATH
  environment:
    PATH: '~/.local/bin:{{ ansible_env.PATH }}'
