- name: Installs common os stuff
  become: yes
  become_user: root
  package:
    name:
      - git
      - sudo
      - git-flow
      - htop
      - tree
      - build-essential
      - cmake
      - acpi
      - libssl-dev
      - libcurl4-gnutls-dev
      - lmodern
      - xzdec
      - libopenblas-dev
      - curl
      - software-properties-common
      - acpi
    state: present

- name: Clone my dotfiles
  git:
    repo: https://github.com/ftan84/.dotfiles
    dest: ~/.dotfiles
    clone: yes
    update: yes

- name: Create .bashrc symlink
  file:
    # src: "{{ ansible_env.PWD }}/roles/core/files/.bashrc"
    src: "~/.dotfiles/roles/core/files/.bashrc"
    path: "~/.bashrc"
    state: link
    force: yes
