- name: Installs common os stuff
  become: yes
  become_user: root
  package:
    name:
      - git-flow
      - htop
      - tree
      - build-essential
      - cmake
      - acpi
      - libssl-dev
      - libcurl4-gnutls-dev
      - lmodern
      - xzdec
      - libopenblas-dev
    state: present

- name: Create .bashrc symlink
  file:
    src: "{{ ansible_env.PWD }}/roles/core/files/.bashrc"
    path: "~/.bashrc"
    state: link
    force: yes
