- name: Install tmux
  become: yes
  package:
    name: tmux
    state: present

- name: Create tmux conf symlink
  file:
    src: "~/.dotfiles/roles/tmux/files/.tmux.conf"
    path: "~/.tmux.conf"
    state: link
    force: yes
