- name: Add alacritty repo
  become: yes
  apt_repository:
    repo: 'ppa:mmstick76/alacritty'

- name: Install alacritty
  become: yes
  package:
    name: alacritty
    state: present

- name: Create alacritty conf symlink
  file:
    src: "~/.dotfiles/roles/alacritty/files/alacritty.yml"
    path: "~/.config/alacritty/alacritty.yml"
    state: link
    force: yes
