# - name: Add neovim repo
#   apt_repository:
#     repo: 'ppa:neovim-ppa/stable'
# 
# - name: Update apt
#   become: yes
#   become_user: root
#   apt:
#     update_cache: yes
# 
# - name: Install neovim and other support
#   become: yes
#   become_user: root
#   package:
#     name:
#       - neovim
#         # - python-dev
#         # - python-pip
#         # - python3-dev
#         # - python3-pip
#     state: present

- name: Download neovim deb file
  get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.7.0/nvim-linux64.deb
    dest: /tmp/nvim-linux64.deb

- name: Install neovim
  become: yes
  apt:
    deb: /tmp/nvim-linux64.deb
