- name: Add neovim repo
  apt_repository:
    repo: 'ppa:neovim-ppa/stable'

- name: Update apt
  become: yes
  become_user: root
  apt:
    update_cache: yes

- name: Install neovim and other support
  become: yes
  become_user: root
  package:
    name:
      - neovim
        # - python-dev
        # - python-pip
        # - python3-dev
        # - python3-pip
    state: present

- name: Install Spacevim
  become: yes
  become_user: root
  command: 'curl -sLf https://spacevim.org/install.sh | bash'

- name: Get Spacevim Install Script
  get_url:
    url: https://spacevim.org/install.sh
    dest: /tmp/install.sh

- name: Install Spacevim
  command: bash /tmp/install.sh

# yamlFloat
