- name: Install alacritty
  kewlfft.aur.aur:
    use: yay
    name: alacritty

- name: Create alacritty config directory
  file:
    path: ~/.config/alacritty
    state: directory

- name: Symlink alacritty config
  file:
    src: "~/.dotfiles/roles/alacritty/files/alacritty.yml"
    path: "~/.config/alacritty/alacritty.yml"
    state: link
    force: yes
